# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='no',
            field=models.CharField(max_length=64),
        ),
    ]
